// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArGfPi0Jvvgr41a7WN8U_h54AsWF8bixY',
    appId: '1:265794026315:web:c68a5e1ed94bb73e19c6ce',
    messagingSenderId: '265794026315',
    projectId: 'itinera-88d50',
    authDomain: 'itinera-88d50.firebaseapp.com',
    databaseURL: 'https://itinera-88d50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itinera-88d50.firebasestorage.app',
    measurementId: 'G-CQ4WJJ4XJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0hUs7itcyRFO8Lby2TaFo7B7Z8G7s3cA',
    appId: '1:265794026315:android:0c75892e9eb1f5d719c6ce',
    messagingSenderId: '265794026315',
    projectId: 'itinera-88d50',
    databaseURL: 'https://itinera-88d50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itinera-88d50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAonNY0CELauKigbLyW7fluwQ-m7aeElGg',
    appId: '1:265794026315:ios:07cee8ef700c336d19c6ce',
    messagingSenderId: '265794026315',
    projectId: 'itinera-88d50',
    databaseURL: 'https://itinera-88d50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itinera-88d50.firebasestorage.app',
    iosClientId: '265794026315-0p1hp1j89h8s8ki1d07prkvg7una0pam.apps.googleusercontent.com',
    iosBundleId: 'com.example.itinera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAonNY0CELauKigbLyW7fluwQ-m7aeElGg',
    appId: '1:265794026315:ios:07cee8ef700c336d19c6ce',
    messagingSenderId: '265794026315',
    projectId: 'itinera-88d50',
    databaseURL: 'https://itinera-88d50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itinera-88d50.firebasestorage.app',
    iosClientId: '265794026315-0p1hp1j89h8s8ki1d07prkvg7una0pam.apps.googleusercontent.com',
    iosBundleId: 'com.example.itinera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArGfPi0Jvvgr41a7WN8U_h54AsWF8bixY',
    appId: '1:265794026315:web:e8d2bf6ea7d19a2519c6ce',
    messagingSenderId: '265794026315',
    projectId: 'itinera-88d50',
    authDomain: 'itinera-88d50.firebaseapp.com',
    databaseURL: 'https://itinera-88d50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itinera-88d50.firebasestorage.app',
    measurementId: 'G-EXJZCZRM3L',
  );
}
